<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Intersql</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
    <div class="container">
        <h1>Books</h1>

        <h2>All books</h2>
        <table class="table mb-5">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Title</th>
                    <th>Price</th>
                    <th>Author</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach($allBooks as $book): ?>
                    <tr>
                        <td><?php echo $book->id ?></td>
                        <td><?php echo $book->title ?></td>
                        <td>$<?php echo $book->price ?></td>
                        <td><?php echo $book->authorName ?></td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>

        <hr>

        <h2>Authors without books</h2>
        <table class="table mb-5">
            <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach($authorsWithoutBooks as $author): ?>
                <tr>
                    <td><?php echo $author->id ?></td>
                    <td><?php echo $author->name ?></td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>

        <hr>

        <h2>Authors with books</h2>
        <table class="table mb-5">
            <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach($authorsWithBooks as $author): ?>
                <tr>
                    <td><?php echo $author->id ?></td>
                    <td><?php echo $author->name ?></td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</body>
</html>